[scheduler]
dry_run = false
log_path = "/home/cheshi/mirror/containers/avocado_scheduler/logs"
max_retries_resource = 10
max_retries_testcase = 2
max_threads = 4

[executor]
container_image = "avocado-cloud:latest"
container_path = "/home/cheshi/mirror/containers/avocado_scheduler"
container_pool = ["ac1", "ac2", "ac3", "ac4"]
dry_run = false
enabled_regions = ["cn-beijing", "cn-shanghai", "cn-shenzhen", "cn-qingdao", "cn-hongkong", "us-west-1"]
log_path = "/home/cheshi/mirror/containers/avocado_scheduler/logs"

image_name = "redhat_8_5_x64_20G_alibase_20211117_copied.qcow2"
keypair = 'cheshi-docker'
pem_file = "/home/cheshi/.pem/cheshi-docker.pem"
