[scheduler]
dry_run = false
log_path = "/home/cheshi/mirror/containers/avocado_scheduler/logs"
max_retries_resource = 10
max_retries_testcase = 3
max_threads = 8

[executor]
container_image = "avocado-cloud:latest"
container_path = "/home/cheshi/mirror/containers/avocado_scheduler"
container_pool_name = "ac"
container_pool_size = 32
dry_run = false
enabled_regions = [
  "cn-beijing",
  "cn-hangzhou",
  "cn-zhangjiakou",
  "cn-shanghai",
  "cn-shenzhen",
  "cn-qingdao",
  "cn-hongkong",
  "us-west-1",
  "ap-southeast-1",
  "eu-central-1",
]
log_path = "/home/cheshi/mirror/containers/avocado_scheduler/logs"

[executor.test]
identity_file = "/home/cheshi/.pem/cheshi-docker.pem"
image_name = "redhat_8_5_x64_20G_alibase_20211117_copied.qcow2"
keypair = "cheshi-docker"
provider = "alibaba"
testcases = """
test_functional_lifecycle.py:LifeCycleTest.test_create_vm_password
test_functional_lifecycle.py:LifeCycleTest.test_create_vm_sshkey
test_functional_checkup.py:GeneralTest.test_collect_information_for_create
test_functional_checkup.py:GeneralTest.test_check_boot_time_create
test_functional_checkup.py:GeneralTest.test_collect_metadata
test_functional_checkup.py:GeneralTest.test_check_cpu_count
test_functional_checkup.py:GeneralTest.test_check_mem_size
test_functional_checkup.py:GeneralTest.test_check_boot_message
test_functional_checkup.py:GeneralTest.test_check_calltrace
test_functional_checkup.py:GeneralTest.test_check_fstab
test_functional_checkup.py:GeneralTest.test_check_bash_prompt
test_functional_checkup.py:GeneralTest.test_check_redhat_release
test_functional_checkup.py:GeneralTest.test_check_selinux_status
test_functional_checkup.py:GeneralTest.test_check_selinux_contexts
test_functional_checkup.py:GeneralTest.test_check_files_controlled_by_rpm
test_functional_checkup.py:GeneralTest.test_check_file_content_integrity_by_rpm
test_functional_checkup.py:GeneralTest.test_check_file_content_integrity_by_diff
test_functional_checkup.py:GeneralTest.test_check_boot_cmdline_parameters
test_functional_checkup.py:GeneralTest.test_check_product_certificate
test_functional_checkup.py:GeneralTest.test_check_package_signature
test_functional_checkup.py:GeneralTest.test_check_hostname
test_functional_checkup.py:GeneralTest.test_check_virt_what
test_functional_checkup.py:GeneralTest.test_check_pv_drivers
test_functional_checkup.py:GeneralTest.test_kdump_status
test_functional_checkup.py:GeneralTest.test_check_image_id
test_functional_checkup.py:GeneralTest.test_check_vulnerabilities
test_functional_network.py:NetworkTest.test_hotplug_nics
test_functional_network.py:NetworkTest.test_coldplug_nics
test_functional_clouddisk.py:CloudDiskTest.test_local_disks
test_functional_clouddisk.py:CloudDiskTest.test_online_attach_detach_cloud_disks
test_functional_clouddisk.py:CloudDiskTest.test_offline_attach_detach_cloud_disks
test_functional_lifecycle.py:LifeCycleTest.test_stop_vm
test_functional_lifecycle.py:LifeCycleTest.test_start_vm
test_functional_checkup.py:GeneralTest.test_collect_information_for_restart
test_functional_lifecycle.py:LifeCycleTest.test_reboot_vm
test_functional_checkup.py:GeneralTest.test_collect_information_for_reboot
test_functional_checkup.py:GeneralTest.test_check_boot_time_reboot
test_functional_lifecycle.py:LifeCycleTest.test_reboot_inside_vm
test_functional_checkup.py:GeneralTest.test_check_yum_repoinfo
test_functional_checkup.py:GeneralTest.test_yum_package_install
test_functional_lifecycle.py:LifeCycleTest.test_delete_vm
test_zcleanup.py:CleanUp.test_release_nics
test_zcleanup.py:CleanUp.test_release_cloud_disks
"""
